esphome:
  name: ${devicetype}-${devicename}

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "gX5V7hhfaPHJ"

  manual_ip:
    static_ip: ${static_ip}
    gateway: 192.168.128.1
    subnet: 255.255.254.0

captive_portal:

text_sensor:
  - platform: version
    name: ${friendly_name} Version
  - platform: wifi_info

time:
  - platform: homeassistant
    id: homeassistant_time



